name: Build Sphinx Documentation

# Trigger the workflow on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest  # The latest Ubuntu environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      # Install dependencies, including Sphinx and the PyData theme
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme

      # Build the Sphinx documentation
      - name: Build documentation
        run: make html  # Build the HTML documentation

      # Upload the built documentation as an artifact
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-html-docs
          path: /build/html

  # Deploy job
  deploy:
    # Add a dependency to the build-docs job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action